# Generated by Django 2.2.9 on 2020-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_auto_20200203_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='end_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='start_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
