# Generated by Django 2.2.9 on 2020-02-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_auto_20200203_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='transporter',
        ),
        migrations.AddField(
            model_name='deal',
            name='transporter',
            field=models.ManyToManyField(to='transportation.Profile'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Vehicle'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', 'Worst Experience'), ('2', 'Bad Experience'), ('3', 'Good Experience'), ('4', 'Very Good Experience'), ('5', 'Excellent Experience')], max_length=1),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_request', models.TextField(default='Handle with Care')),
                ('t_response', models.TextField(default='yes')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Deal')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Profile')),
            ],
        ),
    ]
