# Generated by Django 2.2.9 on 2020-02-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_auto_20200204_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Capacity',
            new_name='capacity',
        ),
    ]
