# Generated by Django 2.2.9 on 2020-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_auto_20200214_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
