# Generated by Django 2.2.9 on 2020-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0012_auto_20200218_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='t_response',
            field=models.TextField(default=''),
        ),
    ]
