# Generated by Django 2.2.9 on 2020-02-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_auto_20200219_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='c_request',
            field=models.TextField(default=''),
        ),
    ]
