# Generated by Django 2.2.9 on 2020-02-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0015_auto_20200219_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='rating',
        ),
    ]
