# Generated by Django 2.2.9 on 2020-02-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0016_remove_deal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='deal_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='transportation.Deal'),
            preserve_default=False,
        ),
    ]
